apiVersion: v1
kind: Service
metadata:
  name: hello-ebpf-api
  labels:
    app: hello-ebpf-api
spec:
  ports:
    - port: 8080
  selector:
    app: hello-ebpf-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ebpf-api
  labels:
    app: hello-ebpf-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-ebpf-api
  template:
    metadata:
      labels:
        app: hello-ebpf-api
    spec:
      containers:
        - name: hello-ebpf-api
          image: hello-ebpf-api:1.0.0
          ports:
            - containerPort: 8080